[project]
name = "zendb"
version = "0.1.0"
description = "CLI para aplicação em bases de dados de regras de negócio construídas no modelo da ferramenta GoRules."
authors = [
    {name = "Laura Dilly", email = "laura.dgm06@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2,<3",
    "python-dotenv>=1.2.2,<2",
    "prompt-toolkit>=3.0.0,<4",
    "typer>=0.15.0",
    "zen-engine (>=2.0.2,<3.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "pydantic (>=2.13.5,<3.0.0)",
]

[project.scripts]
zendb = "zendb.cli:app"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "zendb", from = "src"}]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
